services:
  mysql:
    container_name: 'librarymanagement-mysql-1'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=librarymanagementsystem'
      - 'MYSQL_PASSWORD=Sm@123'
      - 'MYSQL_ROOT_PASSWORD=Sm@123'
      - 'MYSQL_USER=root'
    ports:
      - '3306:3306'